Library Management System/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace Library_Management_System.Models
{
    public class Book
    {
        [Key]
        public int BookId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string ISBN { get; set; }
    }
}

Library Management System/Models/BorrowedBook.cs
using System.ComponentModel.DataAnnotations;

namespace Library_Management_System.Models
{
    public class BorrowedBook
    {
        [Key]
        public int BorrowedId { get; set; }
        [Required]
        public int BookId {  get; set; }
        [Required]
        public int UserId { get;set; }
        [Required]
        public DateTime BorrowDate { get; set; }
        public DateTime? ReturnDate { get; set; }

    }
}

Library Management System/Models/ErrorViewModel.cs
namespace Library_Management_System.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Library Management System/Models/UserLib.cs
using System.ComponentModel.DataAnnotations;

namespace Library_Management_System.Models
{
    public class UserLib
    {
        [Key]
        public int UserId { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public int BookId { get; set; }
    }
}

Library Management System/Controllers/HomeController.cs
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Library_Management_System.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library Management System/Controllers/LibraryController.cs
using Library_Management_System.Data;
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Controllers
{
    public class LibraryController : Controller
    {
        private readonly LibraryDbContext _context;

        public LibraryController(LibraryDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var getallbook = _context.BorrowedBooks.FromSqlRaw("getBorrowedBooksDetails").ToList();
            return View(getallbook);
        }

        public IActionResult getBorrowedBook(int? id)
        {
            var userById = _context.BorrowedBooks.FromSqlRaw($"getBorrowedBooksById {id}").AsEnumerable().FirstOrDefault();
            return View(userById);
        }

        [HttpPost]
        public async Task<IActionResult> updateBorrowedBooks(int id, string userid, string bookid, DateTime bdate, DateTime rdate)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter(){ ParameterName="@id",SqlDbType=System.Data.SqlDbType.VarChar,Value=id},
                new SqlParameter(){ ParameterName="@userid",SqlDbType=System.Data.SqlDbType.VarChar,Value=userid},
                new SqlParameter(){ ParameterName="@bookid",SqlDbType=System.Data.SqlDbType.VarChar,Value=bookid},
                new SqlParameter(){ ParameterName="@bdate",SqlDbType=System.Data.SqlDbType.DateTime,Value=bdate},
                new SqlParameter(){ ParameterName="@rdate",SqlDbType=System.Data.SqlDbType.DateTime,Value=rdate}
            };

            var updateLib = await _context.Database.ExecuteSqlRawAsync($"exec updateBorrowedBook @id,@userid,@bookid,@bdate,@rdate", param);
            if (updateLib == 1)
            {
                return View(updateLib);
            }
            else
            {
                return View(updateLib);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(int id, string userid, string bookid, DateTime bdate, DateTime rdate)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter(){ ParameterName="@id", SqlDbType=System.Data.SqlDbType.VarChar, Value=id},
                new SqlParameter(){ ParameterName="@userid", SqlDbType=System.Data.SqlDbType.VarChar, Value=userid},
                new SqlParameter(){ ParameterName="@bookid", SqlDbType=System.Data.SqlDbType.VarChar, Value=bookid},
                new SqlParameter(){ ParameterName="@bdate", SqlDbType=System.Data.SqlDbType.DateTime, Value=bdate},
                new SqlParameter(){ ParameterName="@rdate", SqlDbType=System.Data.SqlDbType.DateTime, Value=rdate}
            };

            if (id == 0)
            {
                await _context.Database.ExecuteSqlRawAsync("exec insertBorrowedBook @userid, @bookid, @bdate, @rdate", param);
            }
            else
            {
                await _context.Database.ExecuteSqlRawAsync("exec updateBorrowedBook @id, @userid, @bookid, @bdate, @rdate", param);
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpPost, ActionName("DeleteStudent")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStudentConfirmed(int id)
        {
            try
            {
                var student = await _context.BorrowedBooks.FindAsync(id);
                if (student == null)
                {
                    return View("NotFound");
                }

                _context.BorrowedBooks.Remove(student);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error");
            }
        }

    }
}

Library Management System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Library Management System/Views/Library/Index.cshtml
@model IEnumerable<BorrowedBook>
   
<h2>Borrowed Books</h2>

<p>
    <a asp-action="getBorrowedBook">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BorrowedId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BorrowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => student.BorrowedId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.BookId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.BorrowDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => student.ReturnDate)
                </td>
                <td>
                    <a asp-action="getBorrowedBook" asp-route-id="@student.BorrowedId">Edit</a> |
                    @* <a asp-action="DeleteStudent" asp-route-id="@student.BorrowedId" onclick="return confirmAndDelete(@student.BorrowedId);">Delete</a> *@

                    <form asp-action="DeleteStudent" asp-route-id="@student.BorrowedId" method="post" onsubmit="return confirmAndDelete(@student.BorrowedId);">
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Library Management System/Views/Library/getBorrowedBook.cshtml
@model BorrowedBook

@{
    ViewData["Title"] = "Edit";
}
<h1>@ViewData["Title"]</h1>

<h4>View Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="updateBorrowedBooks">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BorrowedId" />

            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <input asp-for="BookId" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="BorrowDate" class="control-label"></label>
                <input asp-for="BorrowDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
 @* @model BorrowedBook

@{
    ViewData["Title"] = Model.BorrowedId != 0 ? "Edit" : "Add";
}

<h1>@ViewData["Title"]</h1>

<h4>View Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOrEdit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BorrowedId" />

            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <input asp-for="BookId" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="BorrowDate" class="control-label"></label>
                <input asp-for="BorrowDate" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
 *@

Library Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Library Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_Management_System.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library Management
                    System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library"
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Library_Management_System - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>